// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8j6hLvGIXyGcunv4HqaqmW3SvHBF49C0',
    appId: '1:763257000142:web:6c0d31a12506d13684009f',
    messagingSenderId: '763257000142',
    projectId: 'hamza-af65e',
    authDomain: 'hamza-af65e.firebaseapp.com',
    storageBucket: 'hamza-af65e.appspot.com',
    measurementId: 'G-EMKN45C84Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrXG0j1I2q0G00QEM876eXuz1gCy4Bs4',
    appId: '1:763257000142:android:1425434c0b0ee45384009f',
    messagingSenderId: '763257000142',
    projectId: 'hamza-af65e',
    storageBucket: 'hamza-af65e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTt7vbrVmgKrncUr3ksaDEFWPSK1M5d0',
    appId: '1:763257000142:ios:d5b8ee629b1d539e84009f',
    messagingSenderId: '763257000142',
    projectId: 'hamza-af65e',
    storageBucket: 'hamza-af65e.appspot.com',
    iosBundleId: 'com.example.mwf08c1f',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbTt7vbrVmgKrncUr3ksaDEFWPSK1M5d0',
    appId: '1:763257000142:ios:d35a2dc19b1a30f384009f',
    messagingSenderId: '763257000142',
    projectId: 'hamza-af65e',
    storageBucket: 'hamza-af65e.appspot.com',
    iosBundleId: 'com.example.mwf08c1f.RunnerTests',
  );
}
